name: Deploy

on:
  push:
    tags:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Import GPG key
      run: >-
        gpg
        --allow-secret-key-import
        --import
        --no-tty
        --batch
        --yes
        <(echo "${{ secrets.GPG_KEY }}")
    - name: Test and deploy to OSSRH
      run: >-
        mvn
        -P release
        -Dgpg.keyName=${{ secrets.GPG_KEYNAME }}
        -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}
        clean test deploy
